### ISSUE TITLE
【内容】文章中是否缺少了图片？

### ISSUE THREAD

**Issue by FWangZil** [gdut-yy/Peopleware-zh#2]
我发现在文内貌似并没有匹配的配图但是有配图的下标，请问日后这部分会有补齐吗？

例如：

[家具警察](http://gdut_yy.gitee.io/doc-pw/ch7.html#%E7%BB%9F%E4%B8%80%E7%9A%84%E5%A1%91%E6%96%99%E5%9C%B0%E4%B8%8B%E5%AE%A4)中的【图 7-1 典型的办公室平面设计】

**Comment by gdut-yy** [comment]
@FWangZil  配图资源不好找，暂时没发现可供使用电子资源。当前的版本主要来自于 OCR，日后有机会会补齐

**Comment by FWangZil** [comment]
好的明白了，之前不知道是OCR来的，大佬辛苦了。
